import { Providers } from "@/redux/provider";
import { CssBaseline } from "@mui/material";
import { Inter } from "next/font/google";
import { ToastContainer } from "react-toastify";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Stock App with Nextjs",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <meta charSet="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <link rel="icon" href="/furkan-logo.jpg" sizes="any" />
      </head>
      <body className={inter.className}>
        <Providers>
          <CssBaseline />
          {children}
          <ToastContainer />
        </Providers>
      </body>
    </html>
  );
}
